parameters:
#    sengine_main.example.class: Sengine\MainBundle\Example

services:
#    sengine_main.example:
#        class: %sengine_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
