parameters:
#    sengine_main.example.class: Sengine\MainBundle\Example

services:
#    sengine_main.example:
#        class: %sengine_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    sengine_main.admin.service:
        class: Sengine\MainBundle\Admin\ServiceAdmin
        arguments: [~, Sengine\MainBundle\Entity\Service, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Материалы, label: Услуги}
